// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAIYIQj2jlfAHNScdEpHX-n26EJW6CoqXY',
    appId: '1:142928827833:web:15b2ee22b6f30a82899268',
    messagingSenderId: '142928827833',
    projectId: 'bejoy-cd9ed',
    authDomain: 'bejoy-cd9ed.firebaseapp.com',
    storageBucket: 'bejoy-cd9ed.appspot.com',
    measurementId: 'G-QN8LBVN8NE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhhp3DwgXo5rfpTUVC9k-l32HQg8m_ytY',
    appId: '1:27134652194:android:23bb2708c9250e4056bf7b',
    messagingSenderId: '27134652194',
    projectId: 'bejoy-57486',
    storageBucket: 'bejoy-57486.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBflxZwSRGSNZeZYCP5O78wc2Vs44PBYkU',
    appId: '1:142928827833:ios:d92e3967cd798431899268',
    messagingSenderId: '142928827833',
    projectId: 'bejoy-cd9ed',
    storageBucket: 'bejoy-cd9ed.appspot.com',
    iosBundleId: 'com.testing.flutterin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBflxZwSRGSNZeZYCP5O78wc2Vs44PBYkU',
    appId: '1:142928827833:ios:457d8b5afc4a9437899268',
    messagingSenderId: '142928827833',
    projectId: 'bejoy-cd9ed',
    storageBucket: 'bejoy-cd9ed.appspot.com',
    iosBundleId: 'com.example.flutterin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAIYIQj2jlfAHNScdEpHX-n26EJW6CoqXY',
    appId: '1:142928827833:web:60787694d0ca906b899268',
    messagingSenderId: '142928827833',
    projectId: 'bejoy-cd9ed',
    authDomain: 'bejoy-cd9ed.firebaseapp.com',
    storageBucket: 'bejoy-cd9ed.appspot.com',
    measurementId: 'G-VJBY25LSK1',
  );

}