// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBn1DGwZ7rmYqt9ZRr2EfJxihdTDwZDbWQ',
    appId: '1:27134652194:web:2dee541b7e4faa9d56bf7b',
    messagingSenderId: '27134652194',
    projectId: 'bejoy-57486',
    authDomain: 'bejoy-57486.firebaseapp.com',
    storageBucket: 'bejoy-57486.appspot.com',
    measurementId: 'G-LT35XH4RH5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhhp3DwgXo5rfpTUVC9k-l32HQg8m_ytY',
    appId: '1:27134652194:android:23bb2708c9250e4056bf7b',
    messagingSenderId: '27134652194',
    projectId: 'bejoy-57486',
    storageBucket: 'bejoy-57486.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIQ1a-y7YAlbpZQALWSRMLuPyxpxf9OJ0',
    appId: '1:27134652194:ios:7065a2bd84fb606556bf7b',
    messagingSenderId: '27134652194',
    projectId: 'bejoy-57486',
    storageBucket: 'bejoy-57486.appspot.com',
    iosBundleId: 'com.example.flutterin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCIQ1a-y7YAlbpZQALWSRMLuPyxpxf9OJ0',
    appId: '1:27134652194:ios:7065a2bd84fb606556bf7b',
    messagingSenderId: '27134652194',
    projectId: 'bejoy-57486',
    storageBucket: 'bejoy-57486.appspot.com',
    iosBundleId: 'com.example.flutterin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBn1DGwZ7rmYqt9ZRr2EfJxihdTDwZDbWQ',
    appId: '1:27134652194:web:6fd47dd5c692d4d356bf7b',
    messagingSenderId: '27134652194',
    projectId: 'bejoy-57486',
    authDomain: 'bejoy-57486.firebaseapp.com',
    storageBucket: 'bejoy-57486.appspot.com',
    measurementId: 'G-ZKP0SZ6SZ7',
  );
}
